# Generated by Django 2.1.3 on 2018-11-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='researches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('keywords', models.CharField(max_length=1000, verbose_name='Keywords')),
                ('keypublication', models.CharField(max_length=1000, verbose_name='Key Publication')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('date', models.DateField(verbose_name='Publishing date')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
    ]
