# Generated by Django 2.1.3 on 2018-11-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=1000, verbose_name='Photo url')),
                ('name', models.CharField(max_length=250, verbose_name='Full name')),
                ('duty', models.CharField(choices=[('Research Assistant', 'Research Assistant'), ('PhD Student', 'PhD Student')], max_length=1000, verbose_name='Position')),
                ('detail', models.TextField(verbose_name='About')),
            ],
            options={
                'verbose_name': 'Assistant',
                'verbose_name_plural': 'Assistants',
            },
        ),
    ]
