# Generated by Django 2.1.3 on 2018-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(choices=[('Concrete Mix Design', 'Concrete Mix Design'), ('Betonarme', 'Betonarme'), ('Structural Mechanics', 'Structural Mechanics'), ('Betonarmede kırılma mekaniği', 'Betonarmede kırılma mekaniği')], default='Betonarme', max_length=1000, verbose_name='Name of course')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('file', models.FileField(upload_to='static/teaching/', verbose_name='Upload')),
                ('content', models.TextField(verbose_name='Write an announcement context')),
            ],
            options={
                'verbose_name': 'Teaching',
                'verbose_name_plural': 'Teachings',
            },
        ),
    ]
