# Generated by Django 2.1.3 on 2018-11-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaching',
            name='content',
        ),
    ]
