# Generated by Django 2.1.3 on 2018-11-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homework',
        ),
        migrations.DeleteModel(
            name='posthomework',
        ),
    ]
