# Generated by Django 2.1.3 on 2018-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_auto_20181126_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('givendate', models.DateField(default='', verbose_name='The date when the homework was given')),
                ('homeworkname', models.CharField(max_length=1000, verbose_name='Homework title')),
                ('lecture', models.CharField(choices=[('Concrete Mix Design', 'Concrete Mix Design'), ('Betonarme', 'Betonarme'), ('Structural Mechanics', 'Structural Mechanics'), ('Betonarmede kırılma mekaniği', 'Betonarmede kırılma mekaniği')], default='Betonarme', max_length=1000, verbose_name='Name of this course')),
                ('desc', models.TextField(default='', verbose_name='explanation for this homework')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
            },
        ),
        migrations.CreateModel(
            name='posthomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentnumber', models.CharField(max_length=1000, verbose_name='Student number')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Recieved date')),
                ('files', models.FileField(upload_to='', verbose_name='Upload a file')),
                ('grade', models.IntegerField(blank=True, default='0')),
                ('coursename', models.CharField(max_length=1000, verbose_name='Course name')),
                ('workname', models.CharField(max_length=1000, verbose_name='Homework name')),
            ],
            options={
                'verbose_name': 'Recieved homework',
                'verbose_name_plural': 'Recieved homeworks',
            },
        ),
    ]
