# Generated by Django 2.1.3 on 2018-12-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_homework_posthomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthomework',
            name='coursename',
            field=models.CharField(choices=[('Concrete Mix Design', 'Concrete Mix Design'), ('Betonarme', 'Betonarme'), ('Structural Mechanics', 'Structural Mechanics'), ('Betonarmede kırılma mekaniği', 'Betonarmede kırılma mekaniği')], default='Betonarme', max_length=1000, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='posthomework',
            name='files',
            field=models.FileField(upload_to='homeworks', verbose_name='Upload your homework'),
        ),
    ]
