# Generated by Django 2.1.3 on 2018-12-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_auto_20181205_0459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
